#!/usr/bin/env python3
"""Rasterise stroke-drawn digits into bitmap rows for src/digits_big.inc.

  python3 tools/gen_digits.py > src/digits_big.inc

Each glyph is a set of centre lines on a 10 x 18 grid (y down), drawn with
a round pen. Sizes are given as the cell height in pixels.
"""
import math

W, H = 10.0, 18.0


def arc(cx, cy, rx, ry, a0, a1, n=24):
    """Points on an ellipse from angle a0 to a1 (degrees, 0 = right, 90 = down)."""
    return [(cx + rx * math.cos(math.radians(a0 + (a1 - a0) * i / n)),
             cy + ry * math.sin(math.radians(a0 + (a1 - a0) * i / n))) for i in range(n + 1)]


def stadium(x0, y0, x1, y1):
    r = (x1 - x0) / 2
    cx = (x0 + x1) / 2
    return arc(cx, y0 + r, r, r, 180, 360) + arc(cx, y1 - r, r, r, 0, 180) + [(x0, y0 + r)]


GLYPHS = {
    '0': [stadium(0, 0, 10, 18)],
    '1': [[(2, 3.5), (5.5, 0), (5.5, 18)]],
    '2': [arc(5, 5, 5, 5, 180, 360) + arc(5, 5, 5, 5, 0, 40, 6) + [(0, 18), (10, 18)]],
    '3': [arc(5, 4.6, 4.6, 4.6, 200, 450) + arc(5, 13, 5, 5, 270, 520)],
    '4': [[(7.5, 18), (7.5, 0), (0, 12.5), (10, 12.5)]],
    '5': [[(9.5, 0), (1, 0), (0.5, 8.2)] + arc(5, 12.6, 5, 5.4, 225, 360 + 160)],
    '6': [arc(5, 13, 5, 5, 0, 360), arc(10, 13, 10, 13, 180, 260, 16)],
    '7': [[(0, 0), (10, 0), (3.5, 18)]],
    '8': [arc(5, 4.5, 4.3, 4.5, 0, 360), arc(5, 13.2, 5, 4.8, 0, 360)],
    '9': [arc(5, 5, 5, 5, 0, 360), arc(0, 5, 10, 13, 0, 80, 16)],
    '.': [[(5, 18), (5, 18)]],
    '-': [[(1.5, 11), (8.5, 11)]],
    '%': [arc(1.2, 3.2, 2.2, 3.2, 0, 360), [(11, 0), (0, 18)], arc(9.8, 14.8, 2.2, 3.2, 0, 360)],
    '\'': [arc(5, 3.5, 3, 3, 0, 360)],          # degree sign
    'C': [arc(5.5, 9, 5, 9, 40, 320)],
}
# narrow glyphs: (left, right) of the grid that is kept
NARROW = {'.': (3, 7), '\'': (1.5, 8.5), '%': (-1, 12)}


def seg_dist(px, py, ax, ay, bx, by):
    dx, dy = bx - ax, by - ay
    l2 = dx * dx + dy * dy
    t = 0.0 if l2 == 0 else max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / l2))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def render(ch, height, pen):
    s = (height - pen) / H
    x0, x1 = NARROW.get(ch, (0, W))
    width = int(round((x1 - x0) * s + pen))
    off = pen / 2 - x0 * s
    segs = []
    for line in GLYPHS[ch]:
        pts = [(off + x * s, pen / 2 + y * s) for x, y in line]
        segs += list(zip(pts, pts[1:])) or [(pts[0], pts[0])]
    rows = []
    for y in range(height):
        row = ''
        for x in range(width):
            hit = 0
            for sy in range(4):
                for sx in range(4):
                    px, py = x + (sx + 0.5) / 4, y + (sy + 0.5) / 4
                    if any(seg_dist(px, py, a[0], a[1], b[0], b[1]) <= pen / 2 for a, b in segs):
                        hit += 1
            row += '#' if hit >= 8 else '.'
        rows.append(row)
    return rows


def emit(name, height, pen):
    print(f'static const glyph_t {name}[] = {{')
    for ch in GLYPHS:
        rows = render(ch, height, pen)
        c = '\\\'' if ch == '\'' else ch
        print(f"  {{'{c}', {{")
        for r in rows:
            print(f'    "{r}",')
        print('  }},')
    print('};')
    print()


print('/* Generated by tools/gen_digits.py. \' is the degree sign. */')
print()
emit('glyphs_32', 32, 4.2)
emit('glyphs_16', 16, 2.2)
