#ifndef DIGITS_H
#define DIGITS_H

#include <stdint.h>

/* Smooth bitmap digits for the status bar, drawn at 1:1.
 * DIGITS_CLOCK: 8 x 13, "0-9 / : -".  DIGITS_SMALL: 6 x 9, "0-9 % -".
 * DIGITS_32 / DIGITS_16: 32 and 16 pixels high, "0-9 . - % C" and ' for
 * the degree sign (generated by tools/gen_digits.py).
 * Unknown characters draw as blanks.
 */
enum { DIGITS_CLOCK, DIGITS_SMALL, DIGITS_32, DIGITS_16 };

int digits_width(const char *s, int font);
void digits_draw(int x, int y, const char *s, int font, uint16_t color);

#endif
