[env:at32f415cbt7]
platform = https://github.com/ArteryTek/platform-arterytekat32.git
board = genericAT32F415CBT7
framework = at32firmlib
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
build_flags = -I${PROJECT_DIR}/include -O2
build_unflags = -Os
