#!/usr/bin/env python3
"""Convert the 8080 game ROM into a C array: bin2c.py rom/game.bin src/game_rom.c"""
import sys
data = open(sys.argv[1], 'rb').read()
lines = ['/* Generated by tools/bin2c.py from %s. Do not edit. */' % sys.argv[1],
         '#include "machine.h"', '',
         'const uint8_t game_rom[GAME_ROM_SIZE] = {']
for i in range(0, len(data), 16):
    lines.append('  ' + ', '.join('0x%02X' % b for b in data[i:i + 16]) + ',')
lines.append('};')
open(sys.argv[2], 'w').write('\n'.join(lines) + '\n')
print('%d bytes -> %s' % (len(data), sys.argv[2]))
